#!/usr/bin/env node
/* Generates the three secrets the API needs and writes them to .env at the
 * repo root WITHOUT clobbering existing keys (use --force to overwrite).
 *
 *   node scripts/generate-secrets.js              # interactive PSK prompt
 *   node scripts/generate-secrets.js --code       # print the current 6-digit code
 *   node scripts/generate-secrets.js --force       # overwrite existing keys
 *
 * After running once, scan the printed base32 secret into Google Authenticator
 * ("Enter a setup key", account name "admin", time-based) — that is the TOTP
 * counterpart for the admin portal login.
 */
import { randomBytes, scryptSync } from 'node:crypto'
import { createHmac } from 'node:crypto'
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { resolve } from 'node:path'
import * as readline from 'node:readline/promises'
import { stdin, stdout } from 'node:process'

const ENV_PATH = resolve(process.cwd(), '.env')

/* ---- base32 (RFC 4648) ---- */
const B32 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'
function base32Encode(buf) {
  let bits = 0, value = 0, out = ''
  for (const b of buf) {
    value = (value << 8) | b
    bits += 8
    while (bits >= 5) {
      out += B32[(value >>> (bits - 5)) & 31]
      bits -= 5
    }
  }
  if (bits > 0) out += B32[(value << (5 - bits)) & 31]
  return out
}
function base32Decode(str) {
  const clean = str.replace(/=+$/, '').replace(/\s/g, '').toUpperCase()
  let bits = 0, value = 0
  const out = []
  for (const ch of clean) {
    const idx = B32.indexOf(ch)
    if (idx === -1) throw new Error(`bad base32 char: ${ch}`)
    value = (value << 5) | idx
    bits += 5
    if (bits >= 8) {
      bits -= 8
      out.push((value >>> bits) & 0xff)
    }
  }
  return Buffer.from(out)
}

/* ---- scrypt password hashing (mirrors server/auth.js) ---- */
function hashPsk(psk) {
  const salt = randomBytes(16)
  const hash = scryptSync(psk, salt, 64, { N: 16384, r: 8, p: 1 })
  return `scrypt$16384$8$1$${salt.toString('base64')}$${hash.toString('base64')}`
}

/* ---- TOTP (RFC 6238) — same algorithm as server/totp.js ---- */
function totpCounter(now = Date.now(), step = 30) {
  return Math.floor(now / 1000 / step)
}
function totpCode(secretB32, counter) {
  const key = base32Decode(secretB32)
  const buf = Buffer.alloc(8)
  buf.writeBigUInt64BE(BigInt(counter))
  const hmac = createHmac('sha1', key).update(buf).digest()
  const off = hmac[hmac.length - 1] & 0x0f
  const bin =
    ((hmac[off] & 0x7f) << 24) |
    ((hmac[off + 1] & 0xff) << 16) |
    ((hmac[off + 2] & 0xff) << 8) |
    (hmac[off + 3] & 0xff)
  return String(bin % 1_000_000).padStart(6, '0')
}

/* ---- .env read/write that preserves existing keys ---- */
function parseEnv(text) {
  const map = new Map()
  for (const line of text.split(/\r?\n/)) {
    const t = line.trim()
    if (!t || t.startsWith('#')) continue
    const eq = t.indexOf('=')
    if (eq === -1) continue
    map.set(t.slice(0, eq).trim(), t.slice(eq + 1).trim())
  }
  return map
}
function writeEnv(map) {
  const lines = ['# auto-generated by scripts/generate-secrets.js — do NOT commit']
  for (const [k, v] of map) lines.push(`${k}=${v}`)
  writeFileSync(ENV_PATH, lines.join('\n') + '\n', { mode: 0o600 })
}

async function ask(rl, q) {
  const a = (await rl.question(q)).trim()
  if (!a) throw new Error('no input provided')
  return a
}

/* ---- main ---- */
const force = process.argv.includes('--force')
const codeMode = process.argv.includes('--code')
const pskOnly = process.argv.includes('--psk')

// --code: read existing TOTP_SECRET from .env and print the current 6 digits
if (codeMode) {
  if (!existsSync(ENV_PATH)) {
    console.error('no .env found — run without --code first to generate secrets')
    process.exit(1)
  }
  const map = parseEnv(readFileSync(ENV_PATH, 'utf8'))
  const secret = map.get('TOTP_SECRET')
  if (!secret) {
    console.error('TOTP_SECRET missing from .env')
    process.exit(1)
  }
  console.log(totpCode(secret, totpCounter()))
  process.exit(0)
}

// --psk: only update ADMIN_PSK_HASH; leave SESSION_SECRET/TOTP_SECRET untouched.
if (pskOnly) {
  if (!existsSync(ENV_PATH)) {
    console.error('no .env found — run without --psk first to generate the other secrets')
    process.exit(1)
  }
  const map = parseEnv(readFileSync(ENV_PATH, 'utf8'))
  const rl = readline.createInterface({ input: stdin, output: stdout })
  try {
    const psk = await ask(rl, 'New admin PSK: ')
    const psk2 = await ask(rl, 'Confirm admin PSK: ')
    if (psk !== psk2) {
      console.error('PSKs did not match. Aborting.')
      process.exit(1)
    }
    map.set('ADMIN_PSK_HASH', hashPsk(psk))
    writeEnv(map)
    console.log(`\nUpdated ADMIN_PSK_HASH in ${ENV_PATH}`)
    console.log('(SESSION_SECRET and TOTP_SECRET untouched.)')
  } finally {
    rl.close()
  }
  process.exit(0)
}

// Read existing .env (if any) so we don't clobber unrelated keys.
const existing = existsSync(ENV_PATH) ? parseEnv(readFileSync(ENV_PATH, 'utf8')) : new Map()

const sessionSecret = existing.get('SESSION_SECRET') && !force
  ? existing.get('SESSION_SECRET')
  : randomBytes(32).toString('hex')

const totpSecret = existing.get('TOTP_SECRET') && !force
  ? existing.get('TOTP_SECRET')
  : base32Encode(randomBytes(20))

// Admin PSK: keep existing hash unless --force AND user supplies a new one.
let pskHash = existing.get('ADMIN_PSK_HASH')
if (force || !pskHash) {
  const rl = readline.createInterface({ input: stdin, output: stdout })
  try {
    const psk = await ask(rl, 'Choose an admin PSK (pre-shared key): ')
    const psk2 = await ask(rl, 'Confirm admin PSK: ')
    if (psk !== psk2) {
      console.error('PSKs did not match. Aborting.')
      process.exit(1)
    }
    pskHash = hashPsk(psk)
  } finally {
    rl.close()
  }
}

const map = new Map(existing)
map.set('API_PORT', existing.get('API_PORT') || '4174')
map.set('SESSION_SECRET', sessionSecret)
map.set('TOTP_SECRET', totpSecret)
map.set('ADMIN_PSK_HASH', pskHash)
writeEnv(map)

console.log(`\nWrote ${ENV_PATH}`)
console.log('\nTOTP setup (Google Authenticator → "Enter a setup key"):')
console.log(`  account:  admin`)
console.log(`  secret:   ${totpSecret}`)
console.log(`  type:     time-based · SHA1 · 6 digits · 30s`)
console.log(`\n  otpauth://totp/aarg.dev:admin?secret=${totpSecret}&issuer=aarg.dev&algorithm=SHA1&digits=6&period=30`)
console.log('\nVerify your phone code matches:')
console.log('  node scripts/generate-secrets.js --code')
